# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('isogeo_notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('wgid', models.AutoField(primary_key=True, serialize=False)),
                ('isogeo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identifiant groupe de travail')),
                ('label', models.CharField(max_length=150, verbose_name='Groupe de travail')),
            ],
            options={
                'verbose_name': 'Groupe de travail',
            },
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AddField(
            model_name='metadata',
            name='isogeo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='metadata',
            name='mdid',
            field=models.AutoField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nom technique'),
        ),
        migrations.AddField(
            model_name='state',
            name='stid',
            field=models.AutoField(default=917, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='md_dt_crea',
            field=models.DateTimeField(blank=True, verbose_name='Création de la métadonnée'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='md_dt_shared_first',
            field=models.DateTimeField(blank=True, verbose_name='Vue la première fois'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='md_dt_shared_last',
            field=models.DateTimeField(blank=True, verbose_name='vue la dernière fois'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='md_dt_update',
            field=models.DateTimeField(blank=True, verbose_name='Dernière modification de la métadonnée'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='rs_dt_crea',
            field=models.DateTimeField(blank=True, verbose_name='Création de la donnée'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='rs_dt_update',
            field=models.DateTimeField(blank=True, verbose_name='Dernière modification de la donnée'),
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='state',
        ),
        migrations.AddField(
            model_name='metadata',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isogeo_notify.State', verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='workgroup',
            field=models.ForeignKey(blank=True, default=967126647004752137391005759231, on_delete=django.db.models.deletion.CASCADE, to='isogeo_notify.Workgroup', verbose_name='Groupe de travail'),
        ),
    ]
