# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isogeo_notify', '0002_auto_20180112_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={'verbose_name': 'Groupe de travail', 'verbose_name_plural': 'Groupes de travail'},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='workgroup',
            field=models.ForeignKey(blank=True, default=1262636175738882869366742746940, on_delete=django.db.models.deletion.CASCADE, to='isogeo_notify.Workgroup', verbose_name='Groupe de travail'),
        ),
        migrations.AlterField(
            model_name='state',
            name='stid',
            field=models.AutoField(default=474, primary_key=True, serialize=False),
        ),
    ]
