"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 1.11.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from configparser import SafeConfigParser
import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY
config = SafeConfigParser()
if os.path.isfile(r"../settings.ini"):
    config.read(r"../settings.ini")
    SECRET_KEY = config.get('web', 'SECRET_KEY')
    DEBUG_SETTING = config.get("web", "DEBUG")
    ISOGEO_CLIENT_ID = config.get("auth", "app_id")
    ISOGEO_CLIENT_SECRET = config.get("auth", "app_secret")
else:
    SECRET_KEY = os.environ.get('ISOGEO_NOTIFY_DB_KEY')

# FORCE DEBUG MODE IF DEV SERVER IS USED
RUNNING_DEVSERVER = (len(sys.argv) > 1 and sys.argv[1] == 'runserver')
if RUNNING_DEVSERVER or int(DEBUG_SETTING):
    DEBUG = True
else:
    DEBUG = False

# HOSTS -----------------------------------------------------------------------
ALLOWED_HOSTS = ["localhost"]

# CACHE -----------------------------------------------------------------------
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    cache_dir = os.path.realpath("tmp")
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': cache_dir,
            'KEY_PREFIX': 'elpaso_',
            'TIMEOUT': 1800,
        }
    }

# APPS -----------------------------------------------------------------------
INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'isogeo_notify.apps.IsogeoNotifyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# DATABASE -------------------------------------------------------------------
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'isogeo.sqlite'),
        'OPTIONS': {
                'timeout': 30,
                        },
                    },
            }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION -------------------------------------------------------
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# ===========================================================================
# APPS SETTINGS
# ===========================================================================

# ADMIN SUIT TEMPLATE
SUIT_CONFIG = {
    # header
    'ADMIN_NAME': "Isogeo to Office",
    'HEADER_DATE_FORMAT': 'l d F Y',
    'HEADER_TIME_FORMAT': 'H:i',

    # menu
    'SEARCH_URL': '/admin/jobs/offer/',
    'MENU_ICONS': {
       'sites': 'icon-leaf',
       'auth': 'icon-lock',
       'jobs': 'icon-briefcase',
    },

    # misc
    'LIST_PER_PAGE': 100
}
